version: '3.8'

services:
  app:
    image: your-dockerhub-username/your-app:latest
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
    ports:
      - "3306:3306"
